target 'BobPullToRefresh', :exclusive => true do
  pod "BobPullToRefresh", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "BobPullToRefresh", :path => "../"

  pod 'Specta', :git => 'https://github.com/specta/specta.git', :tag => 'v0.3.0.beta1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
end
