# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install:
  - brew uninstall xctool
  - brew update
  - brew install xctool --HEAD
  - sudo easy_install cpp-coveralls
script:
  - ./scripts/run-coverage

after_success:
  - ./coveralls.rb --extension m
