#!/bin/bash

xctool  -workspace Example/BobPullToRefresh.xcworkspace \
        -scheme BobPullToRefresh  \
        -configuration Coverage \
        -sdk iphonesimulator \
        -reporter pretty \
        -reporter junit:junit.xml \
        clean build test \
        -test-sdk iphonesimulator7.0

